### ISSUE TITLE
Most tests are failing for me

### ISSUE THREAD

**Issue by hagabaka** [densitypop/Vimmer#8]
On the develop branch, most of the cucumber tests are failing for me. It looks like aruba is getting nil as the exit status of "vimmer install". The output is below and at https://gist.github.com/726711

(in /home/hagabaka/Vimmer)
bundle exec /usr/bin/ruby -I "/usr/lib/ruby/gems/1.9.1/gems/cucumber-0.9.4/lib:lib" "/usr/lib/ruby/gems/1.9.1/gems/cucumber-0.9.4/bin/cucumber" features --format pretty
Using the default profile...
Feature: Setup

  Scenario: Run without .vimmer directory                                                   # features/setup.feature:3
    Given no directory named ".vimmer"                                                      # features/step_definitions/environment_context_steps.rb:6
    When I successfully run "vimmer install 'https://github.com/tpope/vim-awesomemofo.git'" # aruba-0.2.6/lib/aruba/cucumber.rb:98
      Exit status was . Output:
      The plugin vim-awesomemofo.git could not be found
       (RuntimeError)
      features/setup.feature:5:in `When I successfully run "vimmer install 'https://github.com/tpope/vim-awesomemofo.git'"'
    Then a directory named ".vimmer" should exist                                           # aruba-0.2.6/lib/aruba/cucumber.rb:247
    And the file ".vimmer/config" should contain "bundle_path: ~/.vim/bundle"               # aruba-0.2.6/lib/aruba/cucumber.rb:255

  Scenario: Run with .vimmer directory (doesn't overwrite)                                  # features/setup.feature:9
    Given a directory named ".vimmer"                                                       # aruba-0.2.6/lib/aruba/cucumber.rb:62
    And a file named ".vimmer/config" with:                                                 # aruba-0.2.6/lib/aruba/cucumber.rb:66
      """
      bundle_path: ~/.vim/custom_bundle
      """
    When I successfully run "vimmer install 'https://github.com/tpope/vim-awesomemofo.git'" # aruba-0.2.6/lib/aruba/cucumber.rb:98
      Exit status was . Output:
      The plugin vim-awesomemofo.git could not be found
       (RuntimeError)
      features/setup.feature:15:in `When I successfully run "vimmer install 'https://github.com/tpope/vim-awesomemofo.git'"'
    Then the file ".vimmer/config" should contain "bundle_path: ~/.vim/custom_bundle"       # aruba-0.2.6/lib/aruba/cucumber.rb:255

Feature: Install plugin

  Background:                           # features/install.feature:3
    Given a directory named ".vimmer"   # aruba-0.2.6/lib/aruba/cucumber.rb:62
    And a bundle path set for my system # features/step_definitions/environment_context_steps.rb:1
    And I have no plugins installed     # features/step_definitions/plugin_context_steps.rb:1

  Scenario: Install from Github                                                             # features/install.feature:8
    When I successfully run "vimmer install 'https://github.com/tpope/vim-awesomemofo.git'" # aruba-0.2.6/lib/aruba/cucumber.rb:98
      Exit status was . Output:
      The plugin vim-awesomemofo.git could not be found
       (RuntimeError)
      features/install.feature:9:in `When I successfully run "vimmer install 'https://github.com/tpope/vim-awesomemofo.git'"'
    Then a plugin named "vim-awesomemofo" should be installed                               # features/step_definitions/plugin_assertion_steps.rb:1
    And the stdout should contain "vim-awesomemofo has been installed"                      # aruba-0.2.6/lib/aruba/cucumber.rb:187

  Scenario: Install from Github with bad URL                             # features/install.feature:13
    When I run "vimmer install 'https://github.com/tpope/not-found.git'" # aruba-0.2.6/lib/aruba/cucumber.rb:94
    Then I should still not have any plugins installed                   # features/step_definitions/plugin_assertion_steps.rb:6
    And it should fail with:                                             # aruba-0.2.6/lib/aruba/cucumber.rb:162
      """
      The plugin not-found could not be found
      """
      expected "The plugin not-found.git could not be found\n" to include "The plugin not-found could not be found" (RSpec::Expectations::ExpectationNotMetError)
      features/install.feature:16:in `And it should fail with:'

  Scenario: Install from Github with a non-Github URL    # features/install.feature:21
    When I run "vimmer install 'http://example.com/bad'" # aruba-0.2.6/lib/aruba/cucumber.rb:94
    Then I should still not have any plugins installed   # features/step_definitions/plugin_assertion_steps.rb:6
    And it should fail with:                             # aruba-0.2.6/lib/aruba/cucumber.rb:162
      """
      The URL http://example.com/bad is invalid.
      """

  @wip
  Scenario Outline: Install from Github with a front-end Github URL    # features/install.feature:30
    When I successfully run "vimmer install '<URL>'"                   # aruba-0.2.6/lib/aruba/cucumber.rb:98
    Then a plugin named "vim-awesomemofo" should be installed          # features/step_definitions/plugin_assertion_steps.rb:1
    And the stdout should contain "vim-awesomemofo has been installed" # aruba-0.2.6/lib/aruba/cucumber.rb:187

```
Examples: 
  | URL                                      |
  | http://github.com/tpope/vim-awesomemofo  |
  Exit status was . Output:
  vim-awesomemofo has been installed
   (RuntimeError)
  features/install.feature:31:in `When I successfully run "vimmer install '<URL>'"'
  | https://github.com/tpope/vim-awesomemofo |
  Exit status was . Output:
  vim-awesomemofo has been installed
   (RuntimeError)
  features/install.feature:31:in `When I successfully run "vimmer install '<URL>'"'
```

  Scenario: Accept URLs with a "."                                        # features/install.feature:40
    When I run "vimmer install 'http://github.com/tpope/awesomemofo.vim'" # aruba-0.2.6/lib/aruba/cucumber.rb:94
    Then it should pass with:                                             # aruba-0.2.6/lib/aruba/cucumber.rb:162
      """
      awesomemofo.vim has been installed
      """
      expected: 0,
           got: nil (using ==) (RSpec::Expectations::ExpectationNotMetError)
      features/install.feature:42:in `Then it should pass with:'

Feature: Uninstall plugin

  Background:                           # features/uninstall_plugin.feature:3
    Given a directory named ".vimmer"   # aruba-0.2.6/lib/aruba/cucumber.rb:62
    And a bundle path set for my system # features/step_definitions/environment_context_steps.rb:1
    And I have no plugins installed     # features/step_definitions/plugin_context_steps.rb:1

  Scenario: Uninstall from Github                                                           # features/uninstall_plugin.feature:8
    When I successfully run "vimmer install 'https://github.com/tpope/vim-awesomemofo.git'" # aruba-0.2.6/lib/aruba/cucumber.rb:98
      Exit status was . Output:
      The plugin vim-awesomemofo.git could not be found
       (RuntimeError)
      features/uninstall_plugin.feature:9:in `When I successfully run "vimmer install 'https://github.com/tpope/vim-awesomemofo.git'"'
    And I successfully run "vimmer uninstall 'vim-awesomemofo'"                             # aruba-0.2.6/lib/aruba/cucumber.rb:98
    Then I should still not have any plugins installed                                      # features/step_definitions/plugin_assertion_steps.rb:6

  Scenario: Attempt to uninstall a plugin that is not installed # features/uninstall_plugin.feature:13
    When I run "vimmer uninstall not_installed"                 # aruba-0.2.6/lib/aruba/cucumber.rb:94
    Then it should fail with:                                   # aruba-0.2.6/lib/aruba/cucumber.rb:162
      """
      The plugin not_installed is not installed.
      """

Failing Scenarios:
cucumber features/setup.feature:3 # Scenario: Run without .vimmer directory
cucumber features/setup.feature:9 # Scenario: Run with .vimmer directory (doesn't overwrite)
cucumber features/install.feature:8 # Scenario: Install from Github
cucumber features/install.feature:13 # Scenario: Install from Github with bad URL
cucumber features/install.feature:30 # Scenario: Install from Github with a front-end Github URL
cucumber features/install.feature:30 # Scenario: Install from Github with a front-end Github URL
cucumber features/install.feature:40 # Scenario: Accept URLs with a "."
cucumber features/uninstall_plugin.feature:8 # Scenario: Uninstall from Github

10 scenarios (8 failed, 2 passed)
54 steps (8 failed, 11 skipped, 35 passed)
0m27.461s
rake aborted!
Command failed with status (1): [bundle exec /usr/bin/ruby -I "/usr/lib/rub...]
/usr/lib/ruby/1.9.1/rake.rb:993:in `block in sh'
/usr/lib/ruby/1.9.1/rake.rb:1008:in`call'
/usr/lib/ruby/1.9.1/rake.rb:1008:in `sh'
/usr/lib/ruby/1.9.1/rake.rb:1092:in`sh'
/usr/lib/ruby/gems/1.9.1/gems/cucumber-0.9.4/lib/cucumber/rake/task.rb:72:in `run'
/usr/lib/ruby/gems/1.9.1/gems/cucumber-0.9.4/lib/cucumber/rake/task.rb:142:in`block in define_task'
/usr/lib/ruby/1.9.1/rake.rb:634:in `call'
/usr/lib/ruby/1.9.1/rake.rb:634:in`block in execute'
/usr/lib/ruby/1.9.1/rake.rb:629:in `each'
/usr/lib/ruby/1.9.1/rake.rb:629:in`execute'
/usr/lib/ruby/1.9.1/rake.rb:595:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:201:in`mon_synchronize'
/usr/lib/ruby/1.9.1/rake.rb:588:in `invoke_with_call_chain'
/usr/lib/ruby/1.9.1/rake.rb:581:in`invoke'
/usr/lib/ruby/1.9.1/rake.rb:2041:in `invoke_task'
/usr/lib/ruby/1.9.1/rake.rb:2019:in`block (2 levels) in top_level'
/usr/lib/ruby/1.9.1/rake.rb:2019:in `each'
/usr/lib/ruby/1.9.1/rake.rb:2019:in`block in top_level'
/usr/lib/ruby/1.9.1/rake.rb:2058:in `standard_exception_handling'
/usr/lib/ruby/1.9.1/rake.rb:2013:in`top_level'
/usr/lib/ruby/1.9.1/rake.rb:1992:in `run'
/usr/bin/rake:31:in`<main>'

**Comment by joefiorini** [comment]
Thanks for letting me know! Can you try running them against the develop branch now? I think I've fixed the problem. Thanks!

**Comment by hagabaka** [comment]
With the new commits on develop branch, "Scenario: Install from Github with bad URL" now passes, but 7 others still fail.

```
(in /home/hagabaka/Vimmer)
bundle exec /usr/bin/ruby -I "/usr/lib/ruby/gems/1.9.1/gems/cucumber-0.9.4/lib:lib" "/usr/lib/ruby/gems/1.9.1/gems/cucumber-0.9.4/bin/cucumber" features --format pretty
Using the default profile...
Feature: Setup

  Scenario: Run without .vimmer directory                                                   # features/setup.feature:3                                                                    
    Given no directory named ".vimmer"                                                      # features/step_definitions/environment_context_steps.rb:6                                    
    When I successfully run "vimmer install 'https://github.com/tpope/vim-awesomemofo.git'" # aruba-0.2.6/lib/aruba/cucumber.rb:98                                                        
      Exit status was . Output:
      vim-awesomemofo has been installed                                                     
       (RuntimeError)                                                                        
      features/setup.feature:5:in `When I successfully run "vimmer install 'https://github.com/tpope/vim-awesomemofo.git'"'                                                               
    Then a directory named ".vimmer" should exist                                           # aruba-0.2.6/lib/aruba/cucumber.rb:247                                                       
    And the file ".vimmer/config" should contain "bundle_path: ~/.vim/bundle"               # aruba-0.2.6/lib/aruba/cucumber.rb:255                                                       

  Scenario: Run with .vimmer directory (doesn't overwrite)                                  # features/setup.feature:9                                                                    
    Given a directory named ".vimmer"                                                       # aruba-0.2.6/lib/aruba/cucumber.rb:62                                                        
    And a file named ".vimmer/config" with:                                                 # aruba-0.2.6/lib/aruba/cucumber.rb:66                                                        
      """
      bundle_path: ~/.vim/custom_bundle                                                      
      """                                                                                    
    When I successfully run "vimmer install 'https://github.com/tpope/vim-awesomemofo.git'" # aruba-0.2.6/lib/aruba/cucumber.rb:98                                                        
      Exit status was . Output:
      vim-awesomemofo has been installed                                                     
       (RuntimeError)                                                                        
      features/setup.feature:15:in `When I successfully run "vimmer install 'https://github.com/tpope/vim-awesomemofo.git'"'                                                              
    Then the file ".vimmer/config" should contain "bundle_path: ~/.vim/custom_bundle"       # aruba-0.2.6/lib/aruba/cucumber.rb:255                                                       

Feature: Install plugin

  Background:                           # features/install.feature:3
    Given a directory named ".vimmer"   # aruba-0.2.6/lib/aruba/cucumber.rb:62
    And a bundle path set for my system # features/step_definitions/environment_context_steps.rb:1                                                                                        
    And I have no plugins installed     # features/step_definitions/plugin_context_steps.rb:1

  Scenario: Install from Github                                                             # features/install.feature:8                                                                  
    When I successfully run "vimmer install 'https://github.com/tpope/vim-awesomemofo.git'" # aruba-0.2.6/lib/aruba/cucumber.rb:98                                                        
      Exit status was . Output:
      vim-awesomemofo has been installed                                                     
       (RuntimeError)                                                                        
      features/install.feature:9:in `When I successfully run "vimmer install 'https://github.com/tpope/vim-awesomemofo.git'"'                                                             
    Then a plugin named "vim-awesomemofo" should be installed                               # features/step_definitions/plugin_assertion_steps.rb:1                                       
    And the stdout should contain "vim-awesomemofo has been installed"                      # aruba-0.2.6/lib/aruba/cucumber.rb:187                                                       

  Scenario: Install from Github with bad URL                             # features/install.feature:13                                                                                    
    When I run "vimmer install 'https://github.com/tpope/not-found.git'" # aruba-0.2.6/lib/aruba/cucumber.rb:94                                                                           
    Then I should still not have any plugins installed                   # features/step_definitions/plugin_assertion_steps.rb:6                                                          
    And it should fail with:                                             # aruba-0.2.6/lib/aruba/cucumber.rb:162                                                                          
      """
      The plugin not-found could not be found                                                
      """                                                                                    

  Scenario: Install from Github with a non-Github URL    # features/install.feature:21
    When I run "vimmer install 'http://example.com/bad'" # aruba-0.2.6/lib/aruba/cucumber.rb:94                                                                                           
    Then I should still not have any plugins installed   # features/step_definitions/plugin_assertion_steps.rb:6                                                                          
    And it should fail with:                             # aruba-0.2.6/lib/aruba/cucumber.rb:162                                                                                          
      """
      The URL http://example.com/bad is invalid.                                             
      """                                                                                    

  Scenario Outline: Install from Github with a front-end Github URL    # features/install.feature:29                                                                                      
    When I successfully run "vimmer install '<URL>'"                   # aruba-0.2.6/lib/aruba/cucumber.rb:98                                                                             
    Then a plugin named "vim-awesomemofo" should be installed          # features/step_definitions/plugin_assertion_steps.rb:1                                                            
    And the stdout should contain "vim-awesomemofo has been installed" # aruba-0.2.6/lib/aruba/cucumber.rb:187                                                                            

    Examples: 
      | URL                                      |
      | http://github.com/tpope/vim-awesomemofo  |
      Exit status was . Output:
      vim-awesomemofo has been installed                                                     
       (RuntimeError)                                                                        
      features/install.feature:30:in `When I successfully run "vimmer install '<URL>'"'      
      | https://github.com/tpope/vim-awesomemofo |
      Exit status was . Output:
      vim-awesomemofo has been installed                                                     
       (RuntimeError)                                                                        
      features/install.feature:30:in `When I successfully run "vimmer install '<URL>'"'      

  Scenario: Accept URLs with a "."                                        # features/install.feature:39                                                                                   
    When I run "vimmer install 'http://github.com/tpope/awesomemofo.vim'" # aruba-0.2.6/lib/aruba/cucumber.rb:94                                                                          
    Then it should pass with:                                             # aruba-0.2.6/lib/aruba/cucumber.rb:162                                                                         
      """
      awesomemofo.vim has been installed                                                     
      """                                                                                    
      expected: 0,
           got: nil (using ==) (RSpec::Expectations::ExpectationNotMetError)                 
      features/install.feature:41:in `Then it should pass with:'                             

Feature: Uninstall plugin

  Background:                           # features/uninstall_plugin.feature:3
    Given a directory named ".vimmer"   # aruba-0.2.6/lib/aruba/cucumber.rb:62
    And a bundle path set for my system # features/step_definitions/environment_context_steps.rb:1                                                                                        
    And I have no plugins installed     # features/step_definitions/plugin_context_steps.rb:1

  Scenario: Uninstall from Github                                                           # features/uninstall_plugin.feature:8                                                         
    When I successfully run "vimmer install 'https://github.com/tpope/vim-awesomemofo.git'" # aruba-0.2.6/lib/aruba/cucumber.rb:98                                                        
      Exit status was . Output:
      vim-awesomemofo has been installed                                                     
       (RuntimeError)                                                                        
      features/uninstall_plugin.feature:9:in `When I successfully run "vimmer install 'https://github.com/tpope/vim-awesomemofo.git'"'                                                    
    And I successfully run "vimmer uninstall 'vim-awesomemofo'"                             # aruba-0.2.6/lib/aruba/cucumber.rb:98                                                        
    Then I should still not have any plugins installed                                      # features/step_definitions/plugin_assertion_steps.rb:6                                       

  Scenario: Attempt to uninstall a plugin that is not installed # features/uninstall_plugin.feature:13                                                                                    
    When I run "vimmer uninstall not_installed"                 # aruba-0.2.6/lib/aruba/cucumber.rb:94                                                                                    
    Then it should fail with:                                   # aruba-0.2.6/lib/aruba/cucumber.rb:162                                                                                   
      """
      The plugin not_installed is not installed.                                             
      """                                                                                    

Failing Scenarios:
cucumber features/setup.feature:3 # Scenario: Run without .vimmer directory
cucumber features/setup.feature:9 # Scenario: Run with .vimmer directory (doesn't overwrite)
cucumber features/install.feature:8 # Scenario: Install from Github
cucumber features/install.feature:29 # Scenario: Install from Github with a front-end Github URL                                                                                          
cucumber features/install.feature:29 # Scenario: Install from Github with a front-end Github URL                                                                                          
cucumber features/install.feature:39 # Scenario: Accept URLs with a "."
cucumber features/uninstall_plugin.feature:8 # Scenario: Uninstall from Github

10 scenarios (7 failed, 3 passed)
54 steps (7 failed, 11 skipped, 36 passed)
0m26.344s
rake aborted!
Command failed with status (1): [bundle exec /usr/bin/ruby -I "/usr/lib/rub...]
/usr/lib/ruby/1.9.1/rake.rb:993:in `block in sh'
/usr/lib/ruby/1.9.1/rake.rb:1008:in `call'
/usr/lib/ruby/1.9.1/rake.rb:1008:in `sh'
/usr/lib/ruby/1.9.1/rake.rb:1092:in `sh'
/usr/lib/ruby/gems/1.9.1/gems/cucumber-0.9.4/lib/cucumber/rake/task.rb:72:in `run'
/usr/lib/ruby/gems/1.9.1/gems/cucumber-0.9.4/lib/cucumber/rake/task.rb:142:in `block in define_task'
/usr/lib/ruby/1.9.1/rake.rb:634:in `call'
/usr/lib/ruby/1.9.1/rake.rb:634:in `block in execute'
/usr/lib/ruby/1.9.1/rake.rb:629:in `each'
/usr/lib/ruby/1.9.1/rake.rb:629:in `execute'
/usr/lib/ruby/1.9.1/rake.rb:595:in `block in invoke_with_call_chain'
/usr/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/usr/lib/ruby/1.9.1/rake.rb:588:in `invoke_with_call_chain'
/usr/lib/ruby/1.9.1/rake.rb:581:in `invoke'
/usr/lib/ruby/1.9.1/rake.rb:2041:in `invoke_task'
/usr/lib/ruby/1.9.1/rake.rb:2019:in `block (2 levels) in top_level'
/usr/lib/ruby/1.9.1/rake.rb:2019:in `each'
/usr/lib/ruby/1.9.1/rake.rb:2019:in `block in top_level'
/usr/lib/ruby/1.9.1/rake.rb:2058:in `standard_exception_handling'
/usr/lib/ruby/1.9.1/rake.rb:2013:in `top_level'
/usr/lib/ruby/1.9.1/rake.rb:1992:in `run'
/usr/bin/rake:31:in `<main>'
```

**Comment by joefiorini** [comment]
So they are. They were passing a moment ago. BTW, I've pulled in your changes. What operating system are you on?

**Comment by joefiorini** [comment]
Apparently I prematurely pushed after incorrectly applying your changes. I'll have it fixed shortly.

**Comment by joefiorini** [comment]
Patch successfully applied. Sorry about that! Could you please try again? You may need to force pull since I had to rewrite a little of the history to keep things clean.

**Comment by hagabaka** [comment]
I'm on Arch Linux, ruby 1.9.1, aruba 0.2.6. Those 7 tests are still failing for me, but I just noticed that some of aruba's cucumber tests fail the same way. When exit status is supposed to be 0, aruba gets nil. But when it's other values aruba gets them correctly. So I think it's a problem aruba or my installation of it. Do the tests work for you?

Also, strangely those aruba tests fail when I use "rake cucumber", but they pass when I use "cucumber features/*.feature".

**Comment by joefiorini** [comment]
Can you try running `rake` a few times? Does it fail the same way every time? I've had some intermittent problems, but they're very difficult to reproduce. Thanks!

**Comment by hagabaka** [comment]
I think I've found the fix for me. Add something like this before the step definitions:
    Before do
      @aruba_timeout_seconds = 20
    end

If the tests fail intermittently for you, maybe this could help you too, but for me they were failing every time in the same way before I increased the timeout (the default is 1 second). When the process times out, aruba gets a nil exit status. I found this information from aruba's issue aslakhellesoy/aruba#30 and commit aslakhellesoy/aruba@5908786019df49b1ee2f93c29b1469fa8bcc35cb.

I'm not sure if you should increase the timeout in your source or how much. I guess my computer is slower than average.

**Comment by hagabaka** [comment]
I guess I should close this issue.
